Repository MattiaFailla/ToooMail, pull requests merged in 2020-05, with the labels that each got.

#98 Feature/custom registration
  app.py
  py_modules/db_api.py
Labels: Backend, Priority, enhancement

#99 Feature/93
  .gitignore
  app.py
Labels: Backend, enhancement

#96 Adding send_mail function
  app.py
  py_modules/smtp_api.py
Labels: Backend, Priority

#100 Searching in the database and remote server for a given text
  .gitignore
  app.py
  configuration/mail_server.json
  py_modules/db_api.py
  py_modules/imap_api.py
  requirements.txt
Labels: Backend, Priority
